plugins {
    id 'java'

    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

version = mod_version
group = mod_group_id
base.archivesName = "${mod_id}-forge-1.12.2"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mcVersion.set('1.12.2')

    mcpMappingChannel.set('stable')
    mcpMappingVersion.set('39')
    username.set('rivalzin')
}

sourceSets {
    main {
        java.srcDir rootProject.file('core/src/main/java')
        java.srcDir file('../common/src/main/java')

    }

    jeiApi
}

dependencies {
    compileOnly sourceSets.jeiApi.output
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

}
