org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

moddev_version=2.0.147
loom_version=1.17.17
architectury_loom_version=1.17.491

neo_version=21.1.233
loader_version_range=[1,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
modmenu_version=11.0.4

fabric_api_version_1201=0.92.9+1.20.1
modmenu_version_1201=7.2.2

minecraft_version_2119=1.21.9
neo_version_2119=21.9.16-beta
parchment_mappings_version_2119=2025.10.05
fabric_api_version_2119=0.134.1+1.21.9
modmenu_version_2119=16.0.1

minecraft_version_2114=1.21.4
neo_version_2114=21.4.157
fabric_api_version_2114=0.119.2+1.21.4
modmenu_version_2114=13.0.4
jei_mc_2114=1.21.4
jei_version_2114=20.0.0.4
rei_version_2114=18.0.815

minecraft_version_261=26.1.2
neo_version_261=26.1.2.94
fabric_api_version_261=0.151.0+26.1.2
modmenu_version_261=18.0.0

minecraft_version_262=26.2
neo_version_262=26.2.0.45-beta
fabric_api_version_262=0.152.2+26.2
modmenu_version_262=20.0.1

minecraft_version_21111=1.21.11
neo_version_21111=21.11.45
parchment_mappings_version_21111=2025.12.20
fabric_api_version_21111=0.141.4+1.21.11
modmenu_version_21111=17.0.0

forge_version_1201=1.20.1-47.1.47

mod_id=bettersearch
mod_name=Better Search
mod_license=MIT
mod_version=1.4.3
mod_group_id=com.rivalzin.bettersearch
mod_authors=rivalzin

jei_mc_1201=1.20.1
jei_version_1201=15.49.0.188
jei_mc=1.21.1
jei_version=19.44.0.401
jei_mc_2119=1.21.10
jei_version_2119=26.1.1.24
jei_mc_21111=1.21.11
jei_version_21111=27.23.0.71
jei_mc_261=26.1.2
jei_version_261=29.29.0.76
jei_mc_262=26.2
jei_version_262=30.24.0.165

emi_version_1201=1.1.24+1.20.1
emi_version=1.1.24+1.21.1

rei_version_1201=12.1.785
rei_version=16.0.799
rei_version_2119=21.9.813
rei_version_21111=21.11.816
rei_version_261=26.1.819
rei_version_262=26.2.820

forge_version_1192=1.19.2-43.5.1
fabric_api_version_1192=0.77.0+1.19.2
modmenu_version_1192=4.2.0-beta.2
jei_mc_1192=1.19.2
jei_version_1192=11.39.0.1067
emi_version_1192=1.1.24+1.19.2
rei_version_1192=9.2.784

forge_version_1182=1.18.2-40.3.11
fabric_api_version_1182=0.77.0+1.18.2
modmenu_version_1182=3.2.5
jei_mc_1182=1.18.2
jei_version_1182=10.2.1.1002
emi_version_1182=0.7.3+1.18.2
rei_version_1182=8.4.778

forge_version_1165=1.16.5-36.2.42
fabric_api_version_1165=0.42.0+1.16
modmenu_version_1165=1.16.23
rei_version_1165=5.12.385
rei_version_1165_forge=6.5.436
jei_mc_1165=1.16.5
jei_version_1165=7.8.0.1009

minecraft_version_263=26.3
neo_version_263=26.3.0.1-beta
fabric_loader_version_263=0.19.5
fabric_api_version_263=0.160.5+26.3
modmenu_version_263=21.0.0-beta.1
