plugins {
    id 'net.neoforged.moddev.legacyforge'
    id 'java-library'
    id 'idea'
}

version = mod_version
group = mod_group_id
base.archivesName = "${mod_id}-forge-1.20.1"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
    main {
        java.srcDir rootProject.file('core/src/main/java')
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

repositories {
    maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' }
    maven { name = 'EMI'; url = 'https://maven.terraformersmc.com/releases' }

    maven { name = 'BlameJared'; url = 'https://maven.blamejared.com/' }
    mavenCentral()

    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
}

dependencies {

    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:${rei_version_1201}")

    modCompileOnly("dev.emi:emi-forge:${emi_version_1201}")

    modCompileOnly("mezz.jei:jei-${jei_mc_1201}-forge:${jei_version_1201}")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

legacyForge {
    version = project.forge_version_1201

    runs {
        client {
            client()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

mixin {

    add sourceSets.main, 'bettersearch.refmap.json'

    config 'bettersearch-forge.mixins.json'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }

    exclude 'bettersearch.mixins.json'
}

jar {
    manifest {
        attributes([

                'MixinConfigs'           : 'bettersearch-forge.mixins.json,bettersearch-jei.mixins.json,bettersearch-emi.mixins.json,bettersearch-rei.mixins.json',
                'Specification-Title'    : mod_name,
                'Specification-Vendor'   : mod_authors,
                'Specification-Version'  : project.version,
                'Implementation-Title'   : mod_name,
                'Implementation-Version' : project.version,
                'Implementation-Vendor'  : mod_authors
        ])
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
