plugins {

    id 'dev.architectury.loom'
    id 'java-library'
    id 'idea'
}

version = mod_version
group = mod_group_id
base.archivesName = "${mod_id}-forge-1.16.5"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

sourceSets {
    main {
        java.srcDir rootProject.file('core/src/main/java')
        java.srcDir file('../common/src/main/java')
        resources.srcDir file('../common/src/main/resources')
    }
}

repositories {
    maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }

    maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' }

    maven { name = 'BlameJared'; url = 'https://maven.blamejared.com/' }
    maven { name = 'SpongePowered'; url = 'https://repo.spongepowered.org/repository/maven-public/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.16.5"

    def ext = project.extensions.findByName('loom') ?: project.extensions.getByName('minecraft')
    mappings ext.officialMojangMappings()
    forge "net.minecraftforge:forge:${forge_version_1165}"

    modCompileOnly("me.shedaniel:RoughlyEnoughItems-forge:${rei_version_1165_forge}") { transitive = false }

    modCompileOnly("mezz.jei:jei-${jei_mc_1165}:${jei_version_1165}") { transitive = false }

}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }

    exclude 'bettersearch.mixins.json'
}

jar {
    manifest {
        attributes([

                'MixinConfigs'           : 'bettersearch-forge.mixins.json,bettersearch-jei.mixins.json,bettersearch-rei.mixins.json',
                'Specification-Title'    : mod_name,
                'Specification-Vendor'   : mod_authors,
                'Specification-Version'  : project.version,
                'Implementation-Title'   : mod_name,
                'Implementation-Version' : project.version,
                'Implementation-Vendor'  : mod_authors
        ])
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
